#!/sbin/sh

if [ -e /sbin/bootrec-device ]
then
  /sbin/bootrec-device
fi

if [ -s /dev/keycheck -o -e /cache/recovery/boot ]
then
  rm /cache/recovery/boot

  stop ta_rmt_service
  stop rmt_storage
  stop tad
  stop cspsa

  mount -o remount,rw rootfs /
  umount -l /system
  umount -l /data
  umount -l /cache
  umount -l /mnt/sdcard
  rm -r /sdcard
  rm -r /mnt/sdcard
  mkdir /sdcard
  mkdir /tmp
  rm /etc
  mkdir /etc
  cp /recovery.fstab /etc/recovery.fstab
  /sbin/bootrec-device-fs

  echo 1 > /sys/devices/platform/ab8500-i2c.0/ab8500-usb.0/boot_time_device
  setprop service.adb.root 1

  echo 0 > /sys/class/android_usb/android0/enable
  echo 0fce > /sys/class/android_usb/android0/idVendor
  echo 5172 > /sys/class/android_usb/android0/idProduct
  echo mtp,adb > /sys/class/android_usb/android0/functions
  echo 1 > /sys/class/android_usb/android0/enable

  setprop sys.usb.state mtp,adb

  /sbin/recovery &
  /sbin/adbd_rec &
  /sbin/adbd_rec recovery

fi

#continue booting
